// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "danny",
            "email": "zhao_402295440@126.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/captchaImage": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取验证码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "登录"
                ],
                "summary": "获取验证码",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/getInfo": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取用户个人信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "登录"
                ],
                "summary": "获取用户个人信息",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.GetInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "用户登录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "登录"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    },
                    "412": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    },
                    "600": {
                        "description": "用户名密码错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "退出",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "登录"
                ],
                "summary": "退出",
                "responses": {
                    "200": {
                        "description": "退出成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/bzSystem/dept": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询部门列表查询",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部门相关"
                ],
                "summary": "查询部门列表查询",
                "parameters": [
                    {
                        "type": "string",
                        "description": "部门名称",
                        "name": "deptName",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "上级id",
                        "name": "parentId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/response.ResponseData"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "Rows": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/models.SysDeptVo"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "修改部门",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部门相关"
                ],
                "summary": "修改部门",
                "parameters": [
                    {
                        "description": "公司信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SysDeptVo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "添加部门",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部门相关"
                ],
                "summary": "添加部门",
                "parameters": [
                    {
                        "description": "公司信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SysDeptVo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/bzSystem/dept/roleDeptTreeSelect/{roleId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取角色部门",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部门相关"
                ],
                "summary": "获取角色部门",
                "parameters": [
                    {
                        "type": "string",
                        "description": "roleId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.RoleDeptTree"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bzSystem/dept/{deptId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据部门ID获取部门信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部门相关"
                ],
                "summary": "根据部门ID获取部门信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deptId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.SysDeptVo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除部门",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部门相关"
                ],
                "summary": "删除部门",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deptId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/bzSystem/dict/clearCache": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新字典缓存",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典相关"
                ],
                "summary": "更新字典缓存",
                "parameters": [
                    {
                        "description": "字典",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.SysDictDataVo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bzSystem/dict/data": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "修改字典数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典相关"
                ],
                "summary": "修改字典数据",
                "parameters": [
                    {
                        "description": "字典",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SysDictDataVo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "添加字典数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典相关"
                ],
                "summary": "添加字典数据",
                "parameters": [
                    {
                        "description": "字典",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SysDictDataVo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据dictCode获取字典信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典相关"
                ],
                "summary": "根据dictCode获取字典信息",
                "parameters": [
                    {
                        "description": "字典",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.SysDictDataVo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bzSystem/dict/data/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询字典列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典相关"
                ],
                "summary": "查询字典列表",
                "parameters": [
                    {
                        "type": "string",
                        "name": "dictLabel",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "dictType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序规则  降序desc   asc升序",
                        "name": "isAsc",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段",
                        "name": "orderBy",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "第几页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "数量",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/response.ResponseData"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "Rows": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/models.SysDictDataVo"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bzSystem/dict/data/type/{dictType}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询字典列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典相关"
                ],
                "summary": "查询字典列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "dictType",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/response.ResponseData"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "Rows": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/models.SysDictDataVo"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bzSystem/dict/data/{dictCode}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据dictCode获取字典信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典相关"
                ],
                "summary": "根据dictCode获取字典信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "dictCode",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.SysDictDataVo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bzSystem/dict/type": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "修改字典类型数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典相关"
                ],
                "summary": "修改字典类型数据",
                "parameters": [
                    {
                        "description": "字典",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SysDictDataVo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "添加字典类型数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典相关"
                ],
                "summary": "添加字典类型数据",
                "parameters": [
                    {
                        "description": "字典",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SysDictDataVo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据dictCode获取字典类型信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典相关"
                ],
                "summary": "根据dictCode获取字典类型信息",
                "parameters": [
                    {
                        "description": "字典",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/bzSystem/dict/type/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询字典类型列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典相关"
                ],
                "summary": "查询字典类型列表",
                "parameters": [
                    {
                        "type": "string",
                        "name": "dictLabel",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "dictType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序规则  降序desc   asc升序",
                        "name": "isAsc",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段",
                        "name": "orderBy",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "第几页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "数量",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/response.ResponseData"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "Rows": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/models.SysDictDataVo"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bzSystem/dict/type/{dictCode}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据dictCode获取字典类型信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典相关"
                ],
                "summary": "根据dictCode获取字典类型信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "dictCode",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.SysDictDataVo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bzSystem/permission": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "修改权限",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限相关"
                ],
                "summary": "修改权限",
                "parameters": [
                    {
                        "description": "公司信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SysPermissionVo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "添加权限",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限相关"
                ],
                "summary": "添加权限",
                "parameters": [
                    {
                        "description": "公司信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SysPermissionVo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/bzSystem/permission/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询权限列表查询",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限相关"
                ],
                "summary": "查询权限列表查询",
                "parameters": [
                    {
                        "type": "string",
                        "description": "部门名称",
                        "name": "deptName",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "上级id",
                        "name": "parentId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/response.ResponseData"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "Rows": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/models.SysPermissionVo"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bzSystem/permission/{permissionId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据权限ID获取权限信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限相关"
                ],
                "summary": "根据权限ID获取权限信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "permissionId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.SysPermissionVo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除权限",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限相关"
                ],
                "summary": "删除权限",
                "parameters": [
                    {
                        "type": "string",
                        "description": "permissionId",
                        "name": "permissionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/bzSystem/post": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "修改岗位",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "岗位相关"
                ],
                "summary": "修改岗位",
                "parameters": [
                    {
                        "description": "公司信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SysPostVo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "添加岗位",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "岗位相关"
                ],
                "summary": "添加岗位",
                "parameters": [
                    {
                        "description": "公司信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SysPostVo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除岗位",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "岗位相关"
                ],
                "summary": "删除岗位",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "postId",
                        "name": "ids",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/bzSystem/post/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询岗位列表查询",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "岗位相关"
                ],
                "summary": "查询岗位列表查询",
                "parameters": [
                    {
                        "type": "string",
                        "description": "排序规则  降序desc   asc升序",
                        "name": "isAsc",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段",
                        "name": "orderBy",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "第几页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "postCode",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "postName",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "数量",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/response.ResponseData"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "Rows": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/models.SysPostVo"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bzSystem/post/{postId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据岗位ID获取岗位信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "岗位相关"
                ],
                "summary": "根据岗位ID获取岗位信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PostId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.SysPostVo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bzSystem/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询用户列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "查询用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "注册开始时间",
                        "name": "beginTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "部门ID",
                        "name": "deptId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "注册结束时间",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "电话",
                        "name": "phonenumber",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "userName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/response.ResponseData"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "Rows": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/models.SysUserVo"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "修改用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "修改用户",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SysUserDML"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "添加用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "添加用户",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SysUserDML"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统用户"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "description": "userIds",
                        "name": "userIds",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/bzSystem/user/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "获取当前用户信息",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.UserInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bzSystem/user/authRole": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "授权角色",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "授权角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色id",
                        "name": "string",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "string",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/response.ResponseData"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "Rows": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/models.SysUserVo"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bzSystem/user/authRole/{userId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据用户编号获取授权角色",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "根据用户编号获取授权角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "userId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Auth"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bzSystem/user/changeStatus": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "修改用户状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "修改用户状态",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EditUserStatus"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/bzSystem/user/export": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "导出用户",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "系统用户"
                ],
                "summary": "导出用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "注册开始时间",
                        "name": "beginTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "部门ID",
                        "name": "deptId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "注册结束时间",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "电话",
                        "name": "phonenumber",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "userName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "/bzSystem/user/importData": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "导入用户",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统用户"
                ],
                "summary": "导入用户",
                "parameters": [
                    {
                        "type": "file",
                        "description": "file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/bzSystem/user/input": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "导出用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统用户"
                ],
                "summary": "导出用户",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "/bzSystem/user/resetPwd": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "重置密码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "重置密码",
                "parameters": [
                    {
                        "description": "密码",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ResetPwd"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/bzSystem/user/{userId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据用户ID获取用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "根据用户ID获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "userId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Auth"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "baize.Role": {
            "type": "object",
            "properties": {
                "dataScope": {
                    "type": "string"
                },
                "roleId": {
                    "type": "integer"
                }
            }
        },
        "models.Auth": {
            "type": "object",
            "properties": {
                "postIds": {
                    "description": "选择的岗位Id",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "posts": {
                    "description": "岗位",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SysPostVo"
                    }
                },
                "roleIds": {
                    "description": "选择的角色Id",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "roles": {
                    "description": "角色",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SysRoleVo"
                    }
                },
                "user": {
                    "description": "user",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.SysUserVo"
                        }
                    ]
                }
            }
        },
        "models.EditUserStatus": {
            "type": "object",
            "required": [
                "status",
                "userId"
            ],
            "properties": {
                "createBy": {
                    "description": "创建人",
                    "type": "integer"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "string"
                },
                "updateBy": {
                    "description": "修改人",
                    "type": "integer"
                },
                "updateTime": {
                    "description": "修改时间",
                    "type": "integer"
                },
                "userId": {
                    "description": "用户id",
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "models.GetInfo": {
            "type": "object",
            "properties": {
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "models.LoginBody": {
            "type": "object",
            "required": [
                "code",
                "password",
                "username",
                "uuid"
            ],
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                },
                "uuid": {
                    "description": "uuid",
                    "type": "string"
                }
            }
        },
        "models.ResetPwd": {
            "type": "object",
            "required": [
                "password",
                "userId"
            ],
            "properties": {
                "password": {
                    "description": "新密码",
                    "type": "string"
                },
                "userId": {
                    "description": "用户ID",
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "models.RoleDeptTree": {
            "type": "object",
            "properties": {
                "checkedKeys": {
                    "description": "keys",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "depts": {
                    "description": "部门",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SysDeptVo"
                    }
                }
            }
        },
        "models.SysDeptVo": {
            "type": "object",
            "properties": {
                "ancestors": {
                    "description": "祖级列表",
                    "type": "string"
                },
                "createBy": {
                    "description": "创建人",
                    "type": "integer"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "delFag": {
                    "description": "删除标志",
                    "type": "string"
                },
                "deptId": {
                    "description": "id",
                    "type": "string",
                    "example": "0"
                },
                "deptName": {
                    "description": "部门名称",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "leader": {
                    "description": "负责人",
                    "type": "string"
                },
                "orderNum": {
                    "description": "排序",
                    "type": "string"
                },
                "parentId": {
                    "description": "上级id",
                    "type": "string",
                    "example": "0"
                },
                "phone": {
                    "description": "电话",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "string"
                },
                "updateBy": {
                    "description": "修改人",
                    "type": "integer"
                },
                "updateTime": {
                    "description": "修改时间",
                    "type": "integer"
                }
            }
        },
        "models.SysDictDataVo": {
            "type": "object",
            "properties": {
                "createBy": {
                    "description": "创建人",
                    "type": "integer"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "cssClass": {
                    "type": "string"
                },
                "dictCode": {
                    "type": "string",
                    "example": "0"
                },
                "dictLabel": {
                    "type": "string"
                },
                "dictSort": {
                    "type": "integer"
                },
                "dictType": {
                    "type": "string"
                },
                "dictValue": {
                    "type": "string"
                },
                "isDefault": {
                    "type": "string"
                },
                "listClass": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updateBy": {
                    "description": "修改人",
                    "type": "integer"
                },
                "updateTime": {
                    "description": "修改时间",
                    "type": "integer"
                }
            }
        },
        "models.SysPermissionVo": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SysPermissionVo"
                    }
                },
                "createBy": {
                    "description": "创建人",
                    "type": "integer"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "parentId": {
                    "type": "string",
                    "example": "0"
                },
                "parentName": {
                    "type": "string"
                },
                "permissionId": {
                    "type": "string",
                    "example": "0"
                },
                "permissionName": {
                    "type": "string"
                },
                "perms": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updateBy": {
                    "description": "修改人",
                    "type": "integer"
                },
                "updateTime": {
                    "description": "修改时间",
                    "type": "integer"
                }
            }
        },
        "models.SysPostVo": {
            "type": "object",
            "properties": {
                "createBy": {
                    "description": "创建人",
                    "type": "integer"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "postCode": {
                    "type": "string"
                },
                "postId": {
                    "type": "string",
                    "example": "0"
                },
                "postName": {
                    "type": "string"
                },
                "postSort": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updateBy": {
                    "description": "修改人",
                    "type": "integer"
                },
                "updateTime": {
                    "description": "修改时间",
                    "type": "integer"
                }
            }
        },
        "models.SysRole": {
            "type": "object",
            "properties": {
                "dataScope": {
                    "type": "string"
                },
                "roleId": {
                    "type": "integer"
                },
                "roleKey": {
                    "type": "string"
                },
                "roleName": {
                    "type": "string"
                }
            }
        },
        "models.SysRoleVo": {
            "type": "object",
            "properties": {
                "createBy": {
                    "description": "创建人",
                    "type": "integer"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "dataScope": {
                    "type": "string"
                },
                "delFlag": {
                    "type": "string"
                },
                "deptCheckStrictly": {
                    "type": "boolean"
                },
                "permissionCheckStrictly": {
                    "type": "boolean"
                },
                "remark": {
                    "type": "string"
                },
                "roleId": {
                    "type": "string",
                    "example": "0"
                },
                "roleKey": {
                    "type": "string"
                },
                "roleName": {
                    "type": "string"
                },
                "roleSort": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updateBy": {
                    "description": "修改人",
                    "type": "integer"
                },
                "updateTime": {
                    "description": "修改时间",
                    "type": "integer"
                }
            }
        },
        "models.SysUserDML": {
            "type": "object",
            "required": [
                "deptId",
                "nickName",
                "password",
                "sex",
                "userName"
            ],
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "deptId": {
                    "description": "部门ID",
                    "type": "string",
                    "example": "0"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "nickName": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "phonenumber": {
                    "description": "手机号",
                    "type": "string"
                },
                "postIds": {
                    "description": "岗位IDS",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "remake": {
                    "description": "备注",
                    "type": "string"
                },
                "roleIds": {
                    "description": "角色IDS",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sex": {
                    "description": "性别",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "string"
                },
                "userName": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "models.SysUserVo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "createBy": {
                    "description": "创建人",
                    "type": "integer"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "delFlag": {
                    "type": "string"
                },
                "deptId": {
                    "type": "string",
                    "example": "0"
                },
                "deptName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "leader": {
                    "type": "string"
                },
                "nickName": {
                    "type": "string"
                },
                "phonenumber": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "roleId": {
                    "type": "integer"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SysRole"
                    }
                },
                "sex": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updateBy": {
                    "description": "修改人",
                    "type": "integer"
                },
                "updateTime": {
                    "description": "修改时间",
                    "type": "integer"
                },
                "userId": {
                    "type": "string",
                    "example": "0"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "createTime": {
                    "type": "integer"
                },
                "delFlag": {
                    "type": "string"
                },
                "deptId": {
                    "type": "integer"
                },
                "deptName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nickName": {
                    "type": "string"
                },
                "parentId": {
                    "type": "integer"
                },
                "phonenumber": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/baize.Role"
                    }
                },
                "sex": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "userId": {
                    "type": "string",
                    "example": "0"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "models.UserInfo": {
            "type": "object",
            "properties": {
                "posts": {
                    "description": "岗位",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SysPostVo"
                    }
                },
                "roles": {
                    "description": "角色",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SysRoleVo"
                    }
                }
            }
        },
        "response.ResCode": {
            "type": "integer",
            "enum": [
                200,
                401,
                403,
                412,
                500,
                600
            ],
            "x-enum-comments": {
                "Error": "系统异常",
                "Forbidden": "没有权限",
                "Parameter": "参数错误",
                "Success": "成功",
                "Unauthorized": "token失效",
                "Waring": "详情看msg"
            },
            "x-enum-varnames": [
                "Success",
                "Unauthorized",
                "Forbidden",
                "Parameter",
                "Error",
                "Waring"
            ]
        },
        "response.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "相应状态码",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.ResCode"
                        }
                    ]
                },
                "data": {
                    "description": "数据"
                },
                "msg": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.x",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "baize",
	Description:      "baize接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
