name: "baize"
mode: "dev" #dev 开发模式，日志打印到控制台，prod  生产模式，日志不打印控制台
port: 8080
version: 12.0.0
start_time: "2022-08-08"  #此日期用于雪花算法
host: http://localhost:8080
#log:
#  level: info
#  filename: /Volumes/disk01/baizelog/baizelog.log  #默认./log
#  max_size: 200
#  max_age: 30
#  max_backups: 7
datasource:
  mysql:
    driver_name: mysql
    host: 127.0.0.1
    user: root
    password: 123456
    dbname: baize
    port: 3306
    max_open_conns: 200
    max_idle_conns: 50
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    db: 0
    pool_size: 100
token:
  expire_time: 600